export const articles = [
  {
    id: 1,
    title: "SAP S/4 HANA Project Lead – Freelance",
    category: "General",
    image: "/sap-business-meeting.png",
    size: "large",
    date: "January 15, 2024",
    readTime: "5 min read",
    author: "Sarah Johnson",
    views: "2.4k",
    likes: 156,
    excerpt:
      "Discover the latest opportunities in SAP S/4 HANA project leadership and what it takes to succeed in this evolving field.",
    featured: true,
  },
  {
    id: 2,
    title: "The Future Workforce: Why Flexibility Will Define Success",
    category: "Industry Knowledge",
    image: "/flexible-work-meeting.png",
    size: "medium",
    date: "January 12, 2024",
    readTime: "8 min read",
    author: "Michael Chen",
    views: "3.1k",
    likes: 203,
    excerpt:
      "Exploring how workplace flexibility is reshaping the modern workforce and driving business success.",
  },
  {
    id: 3,
    title: "The Role of Contract Workers in Maintaining Business Agility",
    category: "News and Insights",
    image: "/business-agility-meeting.png",
    size: "medium",
    date: "January 10, 2024",
    readTime: "6 min read",
    author: "Emily Rodriguez",
    views: "1.8k",
    likes: 124,
    excerpt:
      "How contract workers are becoming essential for business agility in today's fast-paced market.",
  },
  {
    id: 4,
    title: "Building Diverse Teams: Strategies for Inclusive Hiring",
    category: "Industry Knowledge",
    image: "/diverse-team-meeting.png",
    size: "small",
    date: "January 8, 2024",
    readTime: "4 min read",
    author: "David Thompson",
    views: "2.7k",
    likes: 189,
    excerpt:
      "Practical strategies for creating more diverse and inclusive hiring processes.",
  },
  {
    id: 5,
    title: "Contract vs. Permanent: Making the Right Choice for Your Business",
    category: "News and Insights",
    image: "/business-decision-meeting.png",
    size: "small",
    date: "January 5, 2024",
    readTime: "7 min read",
    author: "Lisa Park",
    views: "1.9k",
    likes: 142,
    excerpt:
      "A comprehensive guide to choosing between contract and permanent hiring strategies.",
  },
  {
    id: 6,
    title: "The Role of a Modern Recruiter in Tech Transformation",
    category: "Industry Knowledge",
    image: "/tech-executive.png",
    size: "small",
    date: "January 3, 2024",
    readTime: "5 min read",
    author: "James Wilson",
    views: "2.2k",
    likes: 167,
    excerpt:
      "How recruiters are adapting to the digital transformation in the tech industry.",
  },
];
